language: node_js
node_js:
  - "stable"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - node_modules

script:
  - cd frontend
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - yarn
#  - echo 'Testing!'
#  - yarn test
  - yarn build
  - git add build/

deploy:
  provider: pages
  cleanup: true
  token: $GH_TOKEN
  local_dir: .
  #  target-branch: stage
  on:
    branch: master