language: node_js
node_js:
  - "stable"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - node_modules



deploy:
  provider: pages
  script:
    - cd frontend
    - echo 'Build starts!!'
    - echo 'Installing Deps!'
    - yarn
    #  - echo 'Testing!'
    #  - yarn test
    - yarn build
#  local_dir: .
  cleanup: false
  token: $GH_TOKEN
  keep_history: true
  deployment_file: true
  on:
    branch: master