version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: echo "this is the test job"
#        command: curl -o- -L https://yarnpkg.com/install.sh | bash -s

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build