orbs:
  yarn: 'itinerisltd/yarn:x.y'
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: echo "this is the build job"
      - run:
          name: yarn --version
          command: yarn --version

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build